// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4MERZnCDK1UOmP3Fn9DDVjfBhMzBx7ZA',
    appId: '1:149171517846:web:3acf4b3ba9fb32f11fc5b7',
    messagingSenderId: '149171517846',
    projectId: 'puzzle-challenge-a49fc',
    authDomain: 'puzzle-challenge-a49fc.firebaseapp.com',
    storageBucket: 'puzzle-challenge-a49fc.appspot.com',
    measurementId: 'G-5KC9XSN7KR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhIcQomyNtWapU09uD4o6I_hWOr0GuPoA',
    appId: '1:149171517846:android:6f406d05ab7fd37c1fc5b7',
    messagingSenderId: '149171517846',
    projectId: 'puzzle-challenge-a49fc',
    storageBucket: 'puzzle-challenge-a49fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgEGIYYdcyLkhBEnMaFpOmQGQ9XcVjID0',
    appId: '1:149171517846:ios:b816143bc661f93e1fc5b7',
    messagingSenderId: '149171517846',
    projectId: 'puzzle-challenge-a49fc',
    storageBucket: 'puzzle-challenge-a49fc.appspot.com',
    iosClientId: '149171517846-n1541puktejlq63341mmgvki1gukc0e8.apps.googleusercontent.com',
    iosBundleId: 'fr.gonzalez.puzzle',
  );
}
